routes/web.php
<?php

use App\Http\Controllers\FallbackController;
use App\Http\Controllers\FicheController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\FichePrepaController;
use App\Http\Controllers\FilterController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// what I add in web.php file hhhh that for me cuz I'm learning 

Route::get('/contact',function () {
  return view('contact');
})->middleware(['auth','verified'])->name('contact');

Route::resource('students',StudentController::class)
  ->only(['index','create','store','show','update','destroy'])
  ->middleware(['auth','verified']);

Route::resource('modules',ModuleController::class)
  ->only(['create','store','show','update','destroy','index'])
  ->middleware(['auth','verified']);



Route::resource('fiches',FicheController::class)
  ->only(['create','store','update','destroy','index','edit'])
  ->middleware(['auth','verified']);


Route::resource('groups',GroupController::class)
  ->only(['create','store','index'])
  ->middleware(['auth','verified']);

Route::get('/filter',FilterController::class)
  ->name('filter.index')
  ->middleware(['auth','verified']);

Route::fallback(FallbackController::class);
//-----------------------------------------------
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/fiches/edit.blade.php
<x-app-layout>
    <div class="w-3/4 mx-auto py-12">
      <h1 class="text-gray-600 font-bold text-2xl my-4">{{__('Ajouter une fiche de préparation')}} </h1>
      <form action="{{route('fiches.update',['fich'=>$fiche])}}" method="POST">
        @csrf
        @method('PATCH')
        <div class="w-full my-2">
          <input 
            class="w-full border-gray-300 rounded-md" 
            type="text" 
            onfocus="this.type='date'" 
            name="dateSeance" 
            placeholder="La date de séance"
            value="{{ old('dateSeance') ? old('dateSeance') : $fiche->dateSeance }}"
          />
        </div>
        @error('dateSeance')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
  
        <div class="w-full my-2 flex items-center gap-1">
          <input 
            class="w-1/2 border-gray-300 rounded-md" 
            type="number" 
            name="dureeTotalHour" 
            value="{{ old('dureeTotalHour') ? old('dureeTotalHour') : $fiche->dureeTotalHour }}"
            placeholder="Durée de la séance (heurs)" min="2" max="7"
          />
          <span class="text-3xl font-bold text-gray-400">:</span>
          <input 
            class="w-1/2 border-gray-300 rounded-md" 
            type="number" 
            name="dureeTotalMin" 
            placeholder="Durée de la séance (minutes)" min="0" max="59"
            value="{{ old('dureeTotalMin') ? old('dureeTotalMin') : $fiche->dureeTotalMin }}"
          />
        </div> 
  
        <div class="w-full my-2">
          <input 
            class="w-full border-gray-300 rounded-md" 
            type="text" 
            name="filiere" 
            value="{{ old('filiere') ? old('filiere') : $fiche->filiere }}"
            placeholder="Filière"/>
        </div> 
         @error('filiere')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
  
        <div class="w-full my-2">
          <select 
            name="module_id"
            class="w-full border-gray-300 rounded-md" 
            onchange="let disOptionM = document.getElementById('module');disOptionM.disabled=true"
          >
            <option 
              value="{{ old('module_id') ? old('module_id') : $fiche->module_id }}" 
              id="module">{{ old('module_id') ? old('module_id') : $fiche->module->name }}</option>
            @if (isset($modules))
            @foreach ($modules as $module)
            <option value="{{ $module->id }}">{{ $module->name }}</option>
            @endforeach
            @endif
          </select>
        </div>
         @error('module_id')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
  
        <div class="w-full my-2">
          <select
            name="group_id"
            onchange="let disOption = document.getElementById('group');disOption.disabled=true" 
            class="w-full border-gray-300 rounded-md">
            <option 
              value="{{ old('group_id') ? old('group_id') : $fiche->group_id }}" 
              id="group">{{ !old('group_id') ? $fiche->group->codeGroup : __('Sélectionnez le groupe') }}</option>
            @if (isset($groups))
            @foreach ($groups as $group)
            <option value="{{$group->id}}">G-{{ $group->codeGroup }}</option>
            @endforeach
            @endif
          </select>
        </div>
         @error('group_id')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
                    
        <div class="border border-gray-300 p-3 bg-white rounded-md w-full my-2 flex justify-center items-center gap-2">
          <input 
            class="cursor-pointer w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600" 
            type="radio" id="firstYear" value="1ér année" name="annee"/>
          
          <label 
            class="cursor-pointer ml-2 text-sm font-medium text-gray-900 dark:text-gray-300"
            for="firstYear">1èr année</label>
          
          <input 
            class="cursor-pointer w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
            type="radio" id="secondYear" checked value="2ème année" name="annee"/>
          
          <label 
            class="cursor-pointer ml-2 text-sm font-medium text-gray-900 dark:text-gray-300"
            for="secondYear">2ème année</label> 
        </div>
         @error('annee')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror 
    
        <div class="w-full">
          <input 
            class="w-full border-gray-300 rounded-md" 
            type="text" 
            name="objectifs" 
            placeholder="Objectifs de la séance"
            value="{{ old('objectifs') ? old('objectifs') : $fiche->objectifs }}"
          />
        </div>
         @error('objectifs')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
  
        <div class="flex w-full my-2">
          <input 
            type="text" 
            name="rappel"
            value="{{ old('rappel') ? old('rappel') : $fiche->rappel }}"
            placeholder="Rappel"
            class="w-5/6 rounded-l-md border-gray-300"
          />
          <input 
            class="w-1/6 rounded-r-md border-l-0 border-gray-300"
            placeholder="Durée (min)"
            name="dureeRappel"
            type="number" 
            value="{{ old('dureeRappel') ? old('dureeRappel') : $fiche->dureeRappel }}"
          />
        </div>
         @error('rappel')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
  
        <div class="flex w-full my-2">
          <input 
            type="text" 
            name="element" 
            value="{{ old('element') ? old('element') : $fiche->element }}"
            placeholder="Eléments de motivation"
            class="w-5/6 rounded-l-md border-gray-300"
          />
          <input 
            class="w-1/6 rounded-r-md border-l-0 border-gray-300"
            placeholder="Durée (min)"
            name="dureeElem"
            value="{{ old('dureeElem') ? old('dureeElem') : $fiche->dureeElem }}"
            type="number" 
          />
        </div>
         @error('element')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
                                    
        <div class="flex w-full my-2">
          <textarea  
            name="planSeance" 
            placeholder="Plan de la Séance"
            class="w-5/6 rounded-l-md border-gray-300"
          >{{ old('planSeance') ? old('planSeance') : $fiche->planSeance }}</textarea>
          <input 
            class="w-1/6 rounded-r-md border-l-0 border-gray-300"
            placeholder="Durée (min)"
            name="dureePlanSeance"
            type="number" 
            value="{{ old('dureePlanSeance') ? old('dureePlanSeance') : $fiche->dureePlanSeance }}"
          />
        </div>
         @error('planSeance')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
  
        <div class="flex w-full my-2">
          <textarea  
            name="strategies" 
            placeholder="Stratégies pédagogiques"
            class="w-5/6 rounded-l-md border-gray-300"
          >{{ old('strategies') ? old('strategies') : $fiche->strategies }}</textarea>
          <input 
            class="w-1/6 rounded-r-md border-l-0 border-gray-300"
            placeholder="Durée (min)"
            name="dureeStrategies"
            value="{{ old('dureeStrategies') ? old('dureeStrategies') : $fiche->dureeStrategies }}"
            type="number" 
          />
        </div>
         @error('strategies')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
  
        <div class="flex w-full my-2">
          <textarea  
            name="developpement" 
            placeholder="Développement"
            class="w-5/6 rounded-l-md border-gray-300"
          >{{ old('developpement') ? old('developpement') : $fiche->developpement }}</textarea>
          <input 
            class="w-1/6 rounded-r-md border-l-0 border-gray-300"
            placeholder="Durée (min)"
            name="dureeDev"
            value="{{ old('dureeDev') ? old('dureeDev') : $fiche->dureeDev }}"
            type="number" 
          />
        </div>
         @error('developpement')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
  
        <div class="flex w-full my-2">
          <textarea  
            name="sythese" 
            placeholder="Synthèse"
            class="w-5/6 rounded-l-md border-gray-300"
          >{{ old('sythese') ? old('sythese') : $fiche->sythese }}</textarea>
          <input 
            class="w-1/6 rounded-r-md border-l-0 border-gray-300"
            placeholder="Durée (min)"
            name="dureeSythese"
            type="number" 
            value="{{ old('dureeSythese') ? old('dureeSythese') : $fiche->dureeSythese }}"
          />
        </div>
         @error('sythese')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
  
        <div class=" my-2 w-full flex">
          <textarea  
            name="evaluation" 
            placeholder="Evaluation"
            class="w-5/6 rounded-l-md border-gray-300"
          >{{ old('evaluation') ? old('evaluation') : $fiche->evaluation }}</textarea>
          <input 
            class="w-1/6 rounded-r-md border-l-0 border-gray-300"
            placeholder="Durée (min)"
            name="dureeEvaluation"
            type="number" 
            value="{{ old('dureeEvaluation') ? old('dureeEvaluation') : $fiche->dureeEvaluation }}"
          />
        </div>
         @error('evaluation')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
  
        <div class="flex w-full my-2">
          <input 
            type="text" 
            name="prochaineSeance"
            placeholder="Prochaine Séance"
            value="{{ old('prochaineSeance') ? old('prochaineSeance') : $fiche->prochaineSeance }}"
            class="w-5/6 rounded-l-md border-gray-300"
          />
          <input 
            class="w-1/6 rounded-r-md border-l-0 border-gray-300"
            placeholder="Durée (min)"
            name="dureeProchaineSeance"
            type="number" 
            value="{{ old('dureeProchaineSeance') ? old('dureeProchaineSeance') : $fiche->dureeProchaineSeance }}"
          />
        </div>
        @error('prochaineSeance')
        <div class="text-red-600 text-center font-bold my-1">
          {{ $message }}  
        </div>
        @enderror
  
        <div class="w-full my-2">
          <button
            class="border border-gray-700 hover:border-0 px-4 py-2 w-40 rounded-md text-gray-700 font-bold hover:text-gray-100 hover:bg-blue-600 transition duration-500"
          >Modifer</button>

          

        </div>
      </form>

      <form
        action="{{ route('fiches.destroy',['fich' =>$fiche]) }}" 
        method="POST" id="supp">
        @csrf
        @method('DELETE')
        <button 
          type="submit"  
          class="border border-gray-700 hover:border-0  px-4 py-2 w-40 rounded-md text-gray-700 font-bold hover:text-gray-100 hover:bg-red-600 transition duration-500">
          Supprimer
        </button>
      </form>

      <script>
        let supp = document.getElementById('supp');
        supp.onsubmit=event=>{
          !confirm('vous-avez sûr pour supprimer le fiche de la date : {{ $fiche->dateSeance }}')?
          event.preventDefault(): '';
        }
      </script>
      
    </div>
  </x-app-layout>
  

resources/views/fiches/index.blade.php
<x-app-layout>
    <!-- messages on screen -->

    @if (session()->has('delete'))
      <h1 class="w-3/4 p-2 bg-red-700 text-gray-100 font-bold text-xl text-center mt-2 rounded-t-md mx-auto">Worning..</h1>
      <div class="bg-red-300 text-red-600 text-center w-3/4 py-4 rounded-b-md mx-auto">
        {{ session()->get('delete') }}
      </div>
    @endif
    @if (session()->has('mesg'))
      <h1 class="w-3/4 p-2 bg-green-700 text-gray-100 font-bold text-xl text-center mt-2 rounded-t-md mx-auto">Success !</h1>
      <div class="bg-green-300 text-green-600 font-bold text-center w-3/4 py-4 rounded-b-md mx-auto">
        {{ session()->get('mesg') }}
      </div>
    @endif
    @if (session()->has('mesgedit'))
      <h1 class="w-3/4 p-2 bg-blue-700 text-gray-100 font-bold text-xl text-center mt-2 rounded-t-md mx-auto">Info !</h1>
      <div class="bg-blue-300 text-blue-600 font-bold text-center w-3/4 py-4 rounded-b-md mx-auto">
        {{ session()->get('mesgedit') }}
      </div>
    @endif

    <!-- button ajouter -->

    <div class="w-3/4 mx-auto my-5">
      <a 
        class="py-2 px-4 bg-green-600 text-gray-100 font-bold rounded-md hover:bg-green-700 transition duration-300"
        href="{{ route('fiches.create') }}">
        Ajouter nouveau fiche
      </a>
    </div>

    <!-- filter form -->

    @if (isset($modules) && isset($groups))
      <form 
        class="my-1 flex items-center mx-auto w-3/4 gap-1" 
        action="{{ route('filter.index') }}" 
        method="GET">
        
        @csrf
        <div class="my-2">
          <select 
            class="border border-gray-300 rounded-md w-full" 
            name="module_id">
            @foreach ($modules as $module)
              <option value="{{ $module->id }}">{{ $module->name }}</option>          
            @endforeach
          </select>
        </div>
  
        <div class="my-2">
          <select 
            class="border border-gray-300 rounded-md w-full"
            name="group_id">
            @foreach ($groups as $group)
              <option value="{{ $group->id }}">{{ $group->codeGroup }}</option>
            @endforeach
          </select>
        </div>
  
        <div>
          <input 
            class="cursor-pointer px-4 py-2 rounded-md bg-slate-500 hover:bg-slate-600 transition durations-400 text-gray-100"
            type="submit" 
            value="Filter">
        </div>
      </form>
      @endif
    

    <!-- all fiches -->
    <div class="w-3/4 mx-auto py-5 ">
      <hr>
      @if (isset($fiches))
      @forelse ($fiches as $fiche)
      <div class="bg-white p-4 rounded-md my-6 shadow shadow-gray-5OO shadow-2xl">
        <a 
          href="{{ route('fiches.edit',['fich'=> $fiche]) }}"
          class="block text-2xl font-bold my-4 mx-auto">Fiche de Préparation : {{ $fiche->dateSeance  }}</a>
  
        <!-- ------------------------------ -->
        <table class="w-full">
          <tr >
            <td class="border border-collapse border-gray-400">
              Date de la séance : {{ $fiche->dateSeance }}
            </td>
            <td class="border border-collapse border-gray-400 p-1">
              Durée de la séance : {{ $fiche->dureeTotalHour }}h{{ $fiche->dureeTotalMin }}
            </td>
          </tr>
          <tr>
            <td class="border border-collapse border-gray-400 p-1">
              Filière : {{ $fiche->filiere }}
            </td>
            <td class="border border-collapse border-gray-400 p-1">
              Anné : {{ $fiche->annee }}
            </td>
          </tr>
  
          <tr>
            <td class="border border-collapse border-gray-400 p-1">
              Module : {{ $fiche->module->name }}
            </td>
            <td class="border border-collapse border-gray-400 p-1">
              Group : {{ $fiche->group->codeGroup }}
            </td>
          </tr>
  
          <tr class="border border-collapse border-gray-400 p-1">
            <td colspan="1">
              Objectifs de la séance : {{ $fiche->objectifs }}
            </td>
          </tr>
        </table>
  
        <!-- ----------------------- -->
  
        <table class="w-full my-4">
          <thead>
              <th colspan="2" class="w-5/6 border border-collapse border-gray-400 p-1">Introduction</th>
              <th class="w-1/6 border border-collapse border-gray-400 p-1">Durée</th>          
          </thead>
          <tbody>
            <tr>
              <td class="w-1/6 border border-collapse border-gray-400 p-1">
                Rappel
              </td>
              <td class="w-3/6 border border-collapse border-gray-400 p-1">
                {{ $fiche->rappel }}
              </td>
              <td class="border border-collapse border-gray-400 p-1">
                {{ $fiche->dureeRappel }}min
              </td>
            </tr>
            
            <tr>
              <td class="w-1/5 border border-collapse border-gray-400 p-1">
                Eléments de motivation
              </td>
              <td class="w-3/5 border border-collapse border-gray-400 p-1">
                {{ $fiche->element }}
              </td>
              <td class="border border-collapse border-gray-400 p-1">
                {{ $fiche->dureeElem }}min
              </td>
            </tr>
  
            <tr>
              <td class="w-1/5 border border-collapse border-gray-400 p-1">
                Plan de la Séance
              </td>
              <td class="w-3/5 border border-collapse border-gray-400 p-1">
                {{ $fiche->planSeance }}
              </td>
              <td class="border border-collapse border-gray-400 p-1">
                {{ $fiche->dureePlanSeance }}min
              </td>
            </tr>
          </tbody>
        </table>
  
        <!-- ----------------------- -->
  
        <table class="w-full my-4">
  
          <thead>
            <th class="border border-gray-400 p-1 w-1/6">
              Stratégies pédagogiques
            </th>
            <th class="border border-gray-400 p-1 w-1/6">
              Développement
            </th>
            <th class="border border-gray-400 p-1 w-4/6">
              Duée
            </th>
          </thead>
          <tbody>
            <tr>
              <td class="border border-gray-400 p-1 w-2/6">
                {{ $fiche->strategies }}
              </td>
              <td class="border border-gray-400 p-1 w-3/6">
                {{ $fiche->developpement }}
              </td>
              <td class="border border-gray-400 p-1 w-1/6">
                {{ ($fiche->dureeDev + $fiche->dureeStrategies) }}min
              </td>
            </tr>
          </tbody>
  
        </table>
  
        <table class="w-full my-4">
          <thead>
              <th colspan="2" class="w-5/6 border border-collapse border-gray-400 p-1">
                Conclusion
              </th>
              <th class="w-1/6 border border-collapse border-gray-400 p-1">Durée</th>          
          </thead>
          <tbody>
            <tr>
              <td class="w-1/5 border border-collapse border-gray-400 p-1">
                Synthèse
              </td>
              <td class="w-3/5 border border-collapse border-gray-400 p-1">
                {{ $fiche->sythese }}
              </td>
              <td class="border border-collapse border-gray-400 p-1">
                {{ $fiche->dureeSythese }}min
              </td>
            </tr>
            
            <tr>
              <td class="w-1/5 border border-collapse border-gray-400 p-1">
                Evaluation
              </td>
              <td class="w-3/5 border border-collapse border-gray-400 p-1">
                {{ $fiche->evaluation }}
              </td>
              <td class="border border-collapse border-gray-400 p-1">
                {{ $fiche->dureeEvaluation }}min
              </td>
            </tr>
  
            <tr>
              <td class="w-1/5 border border-collapse border-gray-400 p-1">
                Prochain Séance
              </td>
              <td class="w-3/5 border border-collapse border-gray-400 p-1">
                {{ $fiche->prochaineSeance }}
              </td>
              <td class="border border-collapse border-gray-400 p-1">
                {{ $fiche->dureeProchaineSeance }}min
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      @empty
      <div class="text-gray-700 text-2xl my-4">
        Non fiche pour affiche !
      </div>
      @endforelse
      @endif
    </div>
  
  </x-app-layout>
  