routes/web.php
<?php

use App\Http\Controllers\FallbackController;
use App\Http\Controllers\FicheController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\FichePrepaController;
use App\Http\Controllers\FilterController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// what I add in web.php file hhhh that for me cuz I'm learning 

Route::get('/contact',function () {
  return view('contact');
})->middleware(['auth','verified'])->name('contact');

Route::resource('students',StudentController::class)
  ->only(['index','create','store','show','update','destroy'])
  ->middleware(['auth','verified']);

Route::resource('modules',ModuleController::class)
  ->only(['create','store','show','update','destroy','index'])
  ->middleware(['auth','verified']);



Route::resource('fiches',FicheController::class)
  ->only(['create','store','update','destroy','index','edit'])
  ->middleware(['auth','verified']);


Route::resource('groups',GroupController::class)
  ->only(['create','store','index'])
  ->middleware(['auth','verified']);

Route::get('/filter',FilterController::class)
  ->name('filter.index')
  ->middleware(['auth','verified']);

Route::fallback(FallbackController::class);
//-----------------------------------------------
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
  use HasFactory;
  protected $fillable = [
    'nom',
    'email',
    'phone',
    'section',
    'image',
    'user_id',
    'group_id'
  ];
  public function user(){
    return $this->belongsTo(User::class);
  }
  public function group(){
    return $this->belongsTo(Group::class);
  }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Group;
use App\Models\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('students.index',[
        'students' => Student::with('user')
          ->latest()
          ->get(),
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.create',[
          'groups' => Group::with('user')->latest()->get(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $validated = $request->validate([
        'nom' => 'required|string|max:255',
        'email' => 'required|string|max:255',
        'phone' => 'required|integer|digits:9',
        'section' => 'required|string',
        'image' => 'required|image|mimes:jpg,png,jpeg',
        'group_id' => 'required|integer',
      ]);
      $new_image_name = uniqid().'-'.$request->nom.'.'.$request->image->extension();
      $request->image->move(public_path('images'),$new_image_name);
      $validated['image'] = $new_image_name;
      $request->user()->students()->create($validated); 

      return redirect(route('students.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
      $this->authorize('update',$student);
      return view('students.show',[
        'student' => $student,
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
      $this->authorize('update',$student);
      $validated = $request->validate([
        'nom' => 'required|string|max:255',
        'email' => 'required|string|max:255',
        'phone' => 'required|integer|digits:9',
        'section' => 'required|string',
        'image' => '',
        'goup_id' =>''
      ]);

      if ($request->image !== null) {
        $new_image_name = uniqid().'-'.$request->nom.'.'.$request->image->extension();
        $request->image->move(public_path('images'),$new_image_name);
        $validated['image'] = $new_image_name;
        $validated['group_id'] = $student->group_id;
        $student->update($validated);
        return redirect(route('students.index'));
      }
      else {
        $validated['image'] = $student->image;
        $validated['group_id'] = $student->group_id;
        $student->update($validated);
      
        return redirect(route('students.index'));
      }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
      $this->authorize('delete',$student);
      $student->delete();
      return redirect(route('students.index'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/students/create.blade.php
<x-app-layout>
  <div class="w-3/4 mx-auto mt-10">
    <h1 class="text-2xl font-bold my-4">Ajouter un étudiant</h1>
    <form action="{{ route('students.store') }}" method="POST" enctype="multipart/form-data">
      @csrf

      <div class="w-full my-2">
        <input 
          type="text" 
          placeholder="Nom" 
          name="nom" 
          value="{{ old('nom') }}"
          class="w-full form-inputi rounded-md border-gray-300 transition duration-500" 
        />
        @error('nom')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
      </div>

      <div class="w-full my-2">
        <input 
          type="text" 
          placeholder="E-mail" 
          name="email" 
          class="w-full form-inputi rounded-md border-gray-300 transition duration-500" 
          value="{{ old('email') }}"
        />
        @error('email')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
      </div>


      <div class="w-full my-2">
        <div class="w-full flex items-center">
          <span class="border py-2 px-1 bg-white rounded-l-md border-r-0">+212</span>
          <input 
            type="number" 
            placeholder="Téléphone" 
            name="phone" 
            class="w-full form-inputi rounded-r-md border-gray-300 transition duration-500" 
            value="{{ old('phone') }}"
          />
        </div>
        @error('phone')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
      </div>

      <div class="w-full my-2">
        <select 
          name="section" 
          onchange="let none=document.querySelector('#none');none.innerHTML='sélectionnez votre rubrique';none.disabled=true;" 
          class="w-full form-inputi rounded-md border-gray-300 transition duration-500"           
        > 
          <option value="{{ old('section') }}" id="none">@if (old('section')) {{ strtoupper(old('section')) }} @else {{ __('sélectionnez la rubrique') }} @endif</option>
          <option value="svt">SVT</option>
          <option value="pc">PC</option>
          <option value="mat">MAT</option>
        </select> 
        @error('section')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
      </div>

      <div class="w-full my-2">
        <select 
          name="group_id" 
          onchange="let disNone=document.querySelector('#disNone');disNone.innerHTML='sélectionnez votre rubrique';disNone.disabled=true;" 
          class="w-full form-inputi rounded-md border-gray-300 transition duration-500"           
        > 
          <option value="{{ old('group_id') }}" id="disNone">@if (old('group_id')) {{ strtoupper(old('group_id')) }} @else {{ __('sélectionnez le groupe') }} @endif</option>
          @foreach ($groups as $group)
            <option value="{{ $group->id }}">G{{ strtoupper($group->codeGroup) }}</option>
          @endforeach
        </select> 
        @error('group_id')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
      </div>

      <div class="w-full my-2">
        <label 
          class="w-full bg-gray-500 hover:bg-gray-700 transition duration-500 py-2 text-gray-100 block text-center rounded-md hover:scale-105 font-bold cursor-pointer" 
          for="image">
          Téléchargez votre image
        </label>
        <input 
          type="file" 
          placeholder="Phone" 
          name="image" 
          id="image"
          class="hidden"
          value="{{old('image')}}"
        />
        @error('image')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
    </div>

    <div>
      <x-primary-button class="bg-green-500">Ajouter</x-app-layout>  
    </div>

    </form> 
  </div>
</x-app-layout>

resources/views/students/index.blade.php
<x-app-layout>
  <div class="w-3/4 mx-auto mt-10">
    <h1 class="text-2xl font-bold my-4">Ajouter un étudiant</h1>
    <div class="flex">
      <h1 class="text-xl font-bold px-8 w-1/6 text-center">Nom</h1>   
      <h1 class="text-xl font-bold px-8 w-1/6 text-center">E-mail</h1>
      <h1 class="text-xl font-bold px-8 w-1/6 text-center">Téléphone</h1>
      <h1 class="text-xl font-bold px-8 w-1/6 text-center">Rubrique</h1>
      <h1 class="text-xl font-bold px-8 w-1/6 text-center">Group</h1>
      <h1 class="text-xl font-bold px-8 text-center ">Image</h1> 
    </div>
    <div class="flex flex-col">
    @foreach ($students as $student)
    <div class="flex items-center my-2 p-2 bg-white rounded-md shadow">
      <p class="px-8 w-1/6 text-center">{{ ucfirst(trans($student->nom)) }}</p>
      <p class="px-8 w-1/6 text-center">{{ $student->email }}</p>
      <p class="px-8 w-1/6 text-center">+212 {{ $student->phone }}</p>
      <p class="px-8 w-1/6 text-center">{{ strtoupper($student->section) }}</p>
      <p class="px-8 w-1/6 text-center">G:{{ strtoupper($student->group->codeGroup) }}</p>
      <p class="px-8 w-1/6 text-center">
        <a href="{{route('students.show',$student)}}"><img class="object-cover w-10 h-10 rounded-full" src="/images/{{$student->image}}" alt="{{ $student->nom }}"/></a>
      </p>
    </div> 
    @endforeach
    </div>
    <div class="my-4">
      <a class="bg-green-500 p-2 rounded-md text-gray-100 hover:bg-green-600 transition duration-300" href="{{route('students.create')}}">Ajouter nouveau etudiant</a>
    </div>
  </div>
</x-app-layout>

resources/views/students/show.blade.php
<x-app-layout>
  <div class="relative w-3/4 mx-auto bg-white mt-20 rounded-xl p-4">
    <form action="{{route('students.update',$student)}}" method="POST" enctype="multipart/form-data">
      @csrf
      @method('PATCH')
        <div class="flex flex-col items-center">
          <img class="w-40 h-40 rounded-full cursor-pointer transition durations-400" src="/images/{{$student->image}}" alt="{{$student->nom}}"/>

          <div class="w-1/4 text-center px-2 py-1 border border-gray-400 text-gray-400 my-4 block rounded-md">
            <label class="w-full px-2 py-1 cursor-pointer block" for="image">{{ __('Télechargez une image') }}</label>
            <input type="file" name="image" class="hidden" value="{{$student->image}}" id="image"/>
          </div>

        </div>
        <div class="w-full my-2">
          <input 
            type="text" 
            placeholder="Nom" 
            name="nom" 
            value="{{$student->nom}}"
            class="w-full form-input rounded-md border-gray-300 transition duration-500" 
          />
          @error('nom')
          <div class="text-red-600 text-center">
            {{ $message }}
          </div>
          @enderror
        </div>

        <div class="w-full my-2">
          <input 
            type="number" 
            placeholder="Télephone" 
            name="phone" 
            value="{{$student->phone}}"
            class="w-full form-input rounded-md border-gray-300 transition duration-500" 
          />
          @error('phone')
          <div class="text-red-600 text-center">
            {{ $message }}
          </div>
          @enderror
        </div>
        
        <div class="w-full my-2">
          <input 
            type="text" 
            placeholder="E-mail" 
            name="email" 
            value="{{$student->email}}"
            class="w-full form-input rounded-md border-gray-300 transition duration-500" 
          />
          @error('email')
          <div class="text-red-600 text-center">
            {{ $message }}
          </div>
          @enderror
        </div>

        <div class="w-full my-2">
          <select 
            name="section" 
            onchange="let none=document.querySelector('#none');none.innerHTML='sélectionnez votre rubrique';none.disabled=true;" 
            class="w-full form-input rounded-md border-gray-300 transition duration-500" 
          >
            <option value="{{$student->section}}" id="none">{{ strtoupper($student->section) }}</option>
            <option value="svt">SVT</option>
            <option value="pc">PC</option>
            <option value="mat">MAT</option>
          </select> 
          @error('section')
          <div class="text-red-600 text-center">
            {{ $message }}
          </div>
          @enderror
        </div>

        <div class="flex gap-4 justify-between items-center">
          <div class="flex gap-4">
            <input type="submit" class="bg-blue-500 px-7 py-2 text-gray-100 rounded-md hover:bg-blue-600" value="{{__('Modifier')}}"/> 
          </div>
          <div>
            <a href="{{route('students.index')}}" class="px-2 py-2 border border-gray-500 rounded-md">{{ __('Back to list') }}</a>   
          </div> 
        </div>
    </form>
    <form action="{{route('students.destroy', $student)}}" method="POST"  class="absolute top-2 right-2" id="del">
      @csrf
      @method('DELETE')
      <x-primary-button  class="border border-gray-500 rounded-md">{{ __('Supprimer') }}</x-primary-button>
    </form>
  </div>
  <script>
    let del = document.getElementById("del");
    del.onsubmit = (e) =>{
      if (!confirm('Êtes-vous sûr vouloir supprimer l\'etudiant : {{$student->nom}} ?')){
        e.preventDefault();
      }
    }
  </script>
</x-app-layout>