routes/web.php
<?php

use App\Http\Controllers\FallbackController;
use App\Http\Controllers\FicheController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\FichePrepaController;
use App\Http\Controllers\FilterController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// what I add in web.php file hhhh that for me cuz I'm learning 

Route::get('/contact',function () {
  return view('contact');
})->middleware(['auth','verified'])->name('contact');

Route::resource('students',StudentController::class)
  ->only(['index','create','store','show','update','destroy'])
  ->middleware(['auth','verified']);

Route::resource('modules',ModuleController::class)
  ->only(['create','store','show','update','destroy','index'])
  ->middleware(['auth','verified']);



Route::resource('fiches',FicheController::class)
  ->only(['create','store','update','destroy','index','edit'])
  ->middleware(['auth','verified']);


Route::resource('groups',GroupController::class)
  ->only(['create','store','index'])
  ->middleware(['auth','verified']);

Route::get('/filter',FilterController::class)
  ->name('filter.index')
  ->middleware(['auth','verified']);

Route::fallback(FallbackController::class);
//-----------------------------------------------
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Module.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Module extends Model
{
  use HasFactory;
  protected $fillable = [
    'nombre',
    'name',
    'masse',
    'user_id',
  ];
  public function user(){
    return $this->belongsTo(User::class);
  }
  public function fiches(){
    return $this->hasMany(Fiche::class);
  }
}

app/Http/Controllers/ModuleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Module;
use Illuminate\Http\Request;

class ModuleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      if (Module::all()){
        return view('modules.create',[
          'modules' => Module::with('user')
            ->latest()
            ->get(),
        ]);
      }
      return view('modules.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $validated = $request->validate([
        'nombre' => 'required|integer|digits:3',
        'name' => 'required|string|max:255',
        'masse' => 'required|integer|min:10|max:300',
      ]);

      $request->user()->modules()->create($validated);
      $notif = 'Ajouter un module valider !';
      return redirect()->route('modules.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function show(Module $module)
    {
      $this->authorize('update',$module);
      return view('modules.show',['module'=>$module]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function edit(Module $module)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Module $module)
    {
        $this->authorize('update',$module);
        $validated = $request->validate([
          'nombre' => 'required|integer|digits:3',
          'name' => 'required|string|max:255',
          'masse' => 'required|integer|min:10|max:300',
        ]);  
        $module->update($validated);
        return redirect(route('modules.create'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function destroy(Module $module)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/modules/create.blade.php
<x-app-layout>
  @if (isset($notif))
  <div class="bg-green-300 py-2 w-full">{{ $notif }}</div>
  @endif
  <div class="my-12 w-3/4 mx-auto">
    <h1 class="my-4 text-gray-500 text-2xl font-bold">Ajouter un module</h1>
    <form action="{{route('modules.store')}}" method="POST">
       
      @csrf
      <div class="w-full my-2">
        <input 
          type="number" 
          placeholder="Nombre module" 
          name="nombre" 
          value="{{ old('nombre') }}"
          class="w-full form-inputi rounded-md border-gray-300 transition duration-500" 
        />
        @error('nombre')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
      </div> 

      <div class="w-full my-2">
        <input 
          type="text" 
          placeholder="Nom module" 
          name="name" 
          value="{{ old('name') }}"
          class="w-full form-inputi rounded-md border-gray-300 transition duration-500" 
        />
        @error('name')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
      </div>

      <div class="w-full my-2">
        <input 
          type="number" 
          placeholder="Masse Heuraire" 
          name="masse" 
          value="{{ old('masse') }}"
          class="w-full form-inputi rounded-md border-gray-300 transition duration-500" 
        />
        @error('masse')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
      </div>
      
      <div>
        <x-primary-button>Ajouter</x-primary-button>
      </div>
    </form>
    @if (isset($modules))
    <div class="mt-12 w-full">
      <div class="flex bg-white p-2 my-2 rounded-md" >
        <span class="w-1/3 text-center text-xl font-bold">{{__('Module')}}</span>
        <span class="w-1/3 text-center text-xl font-bold">{{__('Libile')}}</span> 
        <span class="w-1/3 text-center text-xl font-bold">{{ __('Masse houraire') }}</span>
      </div>
      @foreach ($modules as $module)
      <div class="flex bg-white p-2 my-2 rounded-md" >
        <a href="{{route('modules.show', $module)}}" class="w-1/3 text-center text-xl">M{{ $module->nombre }}</a>
        <span class="w-1/3 text-center text-xl">{{ $module->name }}</span> 
        <span class="w-1/3 text-center text-xl">{{ $module->masse }}h</span>
      </div>
      @endforeach
    </div>
    @endif
  </div>
</x-app-layout>

resources/views/modules/show.blade.php
<x-app-layout>
  <div class="my-12 w-3/4 mx-auto">
  <form action="{{route('modules.update',$module)}}" method="POST">
      @csrf
      @method('PUT')
      <div class="w-full my-2">
        <input 
          type="number" 
          placeholder="Nombre module" 
          name="nombre" 
          value="{{$module->nombre}}"
          class="w-full form-inputi rounded-md border-gray-300 transition duration-500" 
        />
        @error('nombre')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
      </div> 

      <div class="w-full my-2">
        <input 
          type="text" 
          placeholder="Nom module" 
          name="name" 
          value="{{ $module->name }}"
          class="w-full form-inputi rounded-md border-gray-300 transition duration-500" 
        />
        @error('name')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
      </div>

      <div class="w-full my-2">
        <input 
          type="number" 
          placeholder="Masse Heuraire" 
          name="masse" 
          value="{{ $module->masse }}"
          class="w-full form-inputi rounded-md border-gray-300 transition duration-500" 
        />
        @error('masse')
        <div class="text-red-600 text-center">
          {{ $message }}
        </div>
        @enderror
      </div>
      
      <div>
        <x-primary-button>Edit</x-primary-button>
      </div>
    </form>
    </div>
</x-app-layout>